name: Test Inference Service

on:
  workflow_call:
    inputs:
      os-version:
        description: "OS version"
        required: true
        type: string

      python-version:
        description: "Python version"
        required: true
        type: string

      poetry-version:
        description: "Poetry version"
        required: true
        type: string

      working-dir:
        description: "Working directory"
        required: true
        type: string

      should-push-image:
        description: "Whether to push the image to the container registry"
        required: false
        type: boolean
        default: false

    secrets:
      ADVOLVE_GITHUB_TOKEN:
        required: true

      GCLOUD_AUTH:
        required: true

      GCP_PROJECT_ID:
        required: true

      GCP_REGION:
        required: true

      GCP_SA_KEY:
        required: true

      ENV_VARS:
        required: true

jobs:
  test-inference-service:
    name: Test Inference Service
    runs-on: ${{ inputs.os-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install poetry
        run: pipx install poetry==${{ inputs.poetry-version }}

      - name: Setup Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'poetry'

      - name: Install requirements
        run: poetry install

      - name: Configure Google Cloud credentials
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate with Google Cloud
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /dev/stdin
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
        run: |
          echo "${GCLOUD_AUTH}" > /tmp/gcp-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud --version

      - name: Setup Env Vars
        env:
          IMAGE_TAG: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          echo $IMAGE_TAG
          echo "IMAGE_TAG=$(git rev-parse --short $IMAGE_TAG)" >> $GITHUB_ENV
          echo "${{ secrets.ENV_VARS }}" > ${{ inputs.working-dir }}/vars.env

      - name: Download Model
        working-directory: ${{ inputs.working-dir }}
        run:
          make download

      - name: Build Image
        working-directory: ${{ inputs.working-dir }}
        run: make build

      - name: Push Image
        if: ${{ inputs.should-push-image }}
        working-directory: ${{ inputs.working-dir }}
        run: make push

      - name: Start Server
        working-directory: ${{ inputs.working-dir }}
        run: make start-ci

      - name: Test Inference Service
        working-directory: ${{ inputs.working-dir }}
        run: make predict

      - name: Stop Server
        working-directory: ${{ inputs.working-dir }}
        if: always()
        run: make stop
